/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phonebook;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Oliva
 */
public class emenemsmain extends javax.swing.JFrame implements emenemsinter {
    public DefaultListModel model = new DefaultListModel<>();
    /**
     * Creates new form emenemsmain
     */
    public emenemsmain() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEntryDialog = new javax.swing.JDialog();
        panel2 = new java.awt.Panel();
        BirthDayInput = new javax.swing.JTextField();
        NumberInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AddressInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AddEntryBackButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BirthMonthInput = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BirthYearInput = new javax.swing.JTextField();
        LastNameInput = new javax.swing.JTextField();
        FirstNameInput = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        UpdateEntryDialog = new javax.swing.JDialog();
        panel4 = new java.awt.Panel();
        jLabel35 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        BirthDayTextField = new javax.swing.JTextField();
        BirthMonthTextField = new javax.swing.JTextField();
        NumberTextField = new javax.swing.JTextField();
        BirthYearTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        SearchDialog = new javax.swing.JDialog();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(model);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LastNameOutput = new javax.swing.JLabel();
        FirstNameOutput = new javax.swing.JLabel();
        BirthdayOutput = new javax.swing.JLabel();
        NumberOutput = new javax.swing.JLabel();
        AddressOutput = new javax.swing.JLabel();
        EmailOutput = new javax.swing.JLabel();
        UpdateEntry = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        DeleteEntry = new javax.swing.JButton();
        AddEntry = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();

        AddEntryDialog.setBackground(new java.awt.Color(204, 255, 204));
        AddEntryDialog.setMinimumSize(new java.awt.Dimension(400, 438));
        AddEntryDialog.setModal(true);
        AddEntryDialog.setPreferredSize(new java.awt.Dimension(400, 438));

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setForeground(new java.awt.Color(204, 255, 204));
        panel2.setMaximumSize(null);
        panel2.setMinimumSize(new java.awt.Dimension(400, 438));
        panel2.setName(""); // NOI18N
        panel2.setPreferredSize(new java.awt.Dimension(400, 438));

        BirthDayInput.setBackground(new java.awt.Color(204, 255, 204));
        BirthDayInput.setToolTipText("");
        BirthDayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayInputActionPerformed(evt);
            }
        });
        BirthDayInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayInput,2);
            }
        });

        NumberInput.setBackground(new java.awt.Color(204, 255, 204));

        EmailInput.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("First Name:");

        AddressInput.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("Last Name:");

        SubmitButton.setBackground(new java.awt.Color(153, 255, 153));
        SubmitButton.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText("Birthday:");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setText("Create Phonebook");

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("Number:");

        AddEntryBackButton.setBackground(new java.awt.Color(153, 255, 153));
        AddEntryBackButton.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        AddEntryBackButton.setText("Back");
        AddEntryBackButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddEntryBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryBackButtonActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setText("Address:");

        BirthMonthInput.setBackground(new java.awt.Color(204, 255, 204));
        BirthMonthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthInputActionPerformed(evt);
            }
        });
        BirthMonthInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthInput,2);
            }
        });

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 204));
        jLabel12.setText("Email:");

        BirthYearInput.setBackground(new java.awt.Color(204, 255, 204));
        BirthYearInput.setToolTipText("");
        BirthYearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthYearInputActionPerformed(evt);
            }
        });
        BirthYearInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearInput,4);
            }
        });

        LastNameInput.setBackground(new java.awt.Color(204, 255, 204));
        LastNameInput.setToolTipText("");
        LastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameInputActionPerformed(evt);
            }
        });

        FirstNameInput.setBackground(new java.awt.Color(204, 255, 204));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 255, 204));
        jLabel21.setText("Day                   Month                 Year");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(LastNameInput))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)))
                        .addGap(30, 30, 30)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailInput)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthYearInput))
                            .addComponent(AddressInput)
                            .addComponent(NumberInput)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(AddEntryBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(81, 81, 81))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEntryBackButton)
                    .addComponent(SubmitButton))
                .addGap(94, 94, 94))
        );

        NumberInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberInput,11);
            }
        });
        SubmitButton.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                String fullDate = BirthDayInput.getText()+"/"+BirthMonthInput.getText()+"/"+BirthYearInput.getText();
                if (FirstNameInput.getText().isEmpty()||LastNameInput.getText().isEmpty()||BirthDayInput.getText().isEmpty()||AddressInput.getText().isEmpty()||EmailInput.getText().isEmpty()||NumberInput.getText().isEmpty()){

                    System.out.println("Error: Incomplete/Improper Data");
                    JOptionPane.showMessageDialog(AddEntryDialog,"Error: Incomplete/Improper","Error",JOptionPane.ERROR_MESSAGE);
                } else{
                    emenemsinter.addRow(FirstNameInput.getText(), LastNameInput.getText(), fullDate, AddressInput.getText(), EmailInput.getText(), NumberInput.getText());
                    int index = (model.isEmpty())? 0:indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText()));
                    model.add(index, FirstNameInput.getText());
                    System.out.println(indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText())));
                    AddEntryDialog.dispose();
                }
            }
        });

        javax.swing.GroupLayout AddEntryDialogLayout = new javax.swing.GroupLayout(AddEntryDialog.getContentPane());
        AddEntryDialog.getContentPane().setLayout(AddEntryDialogLayout);
        AddEntryDialogLayout.setHorizontalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEntryDialogLayout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        AddEntryDialogLayout.setVerticalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UpdateEntryDialog.setMinimumSize(new java.awt.Dimension(400, 438));
        UpdateEntryDialog.setPreferredSize(new java.awt.Dimension(400, 438));
        UpdateEntryDialog.setResizable(false);

        panel4.setBackground(new java.awt.Color(51, 51, 51));
        panel4.setForeground(new java.awt.Color(204, 255, 204));
        panel4.setMaximumSize(new java.awt.Dimension(52525252, 525252));
        panel4.setMinimumSize(new java.awt.Dimension(400, 438));
        panel4.setName(""); // NOI18N

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 255, 204));
        jLabel35.setText("Update Phonebook");

        UpdateButton.setBackground(new java.awt.Color(153, 255, 153));
        UpdateButton.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 204));
        jLabel14.setText("Address:");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 255, 204));
        jLabel18.setText("Birthday:");

        LastNameTextField.setBackground(new java.awt.Color(204, 255, 204));
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 255, 204));
        jLabel20.setText("Number:");

        FirstNameTextField.setBackground(new java.awt.Color(204, 255, 204));
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        BirthDayTextField.setBackground(new java.awt.Color(204, 255, 204));
        BirthDayTextField.setName(""); // NOI18N
        BirthDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayTextFieldActionPerformed(evt);
            }
        });
        BirthDayTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayTextField,2);
            }
        });

        BirthMonthTextField.setBackground(new java.awt.Color(204, 255, 204));
        BirthMonthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthTextFieldActionPerformed(evt);
            }
        });

        NumberTextField.setBackground(new java.awt.Color(204, 255, 204));
        NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTextFieldActionPerformed(evt);
            }
        });

        BirthYearTextField.setBackground(new java.awt.Color(204, 255, 204));

        EmailTextField.setBackground(new java.awt.Color(204, 255, 204));
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 255, 204));
        jLabel23.setText("Email:");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 204));
        jLabel16.setText("First Name:");

        AddressTextField.setBackground(new java.awt.Color(204, 255, 204));
        AddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 255, 204));
        jLabel17.setText("Last Name:");

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 255, 204));
        jLabel32.setText("Day                   Month                 Year");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel14))))
                        .addGap(18, 18, 18)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addComponent(BirthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthMonthTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LastNameTextField)
                            .addComponent(AddressTextField)
                            .addComponent(EmailTextField)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(81, 81, 81))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel18))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BirthMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(UpdateButton))
                .addGap(65, 65, 65))
        );

        BirthMonthTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthTextField,2);
            }
        });
        NumberTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberTextField,11);
            }
        });
        BirthYearTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearTextField,4);
            }
        });

        javax.swing.GroupLayout UpdateEntryDialogLayout = new javax.swing.GroupLayout(UpdateEntryDialog.getContentPane());
        UpdateEntryDialog.getContentPane().setLayout(UpdateEntryDialogLayout);
        UpdateEntryDialogLayout.setHorizontalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        UpdateEntryDialogLayout.setVerticalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout SearchDialogLayout = new javax.swing.GroupLayout(SearchDialog.getContentPane());
        SearchDialog.getContentPane().setLayout(SearchDialogLayout);
        SearchDialogLayout.setHorizontalGroup(
            SearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SearchDialogLayout.setVerticalGroup(
            SearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 300));

        panel1.setBackground(new java.awt.Color(153, 255, 153));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        for (int i =0; i<emenemsinter.firstNameList.size();i++){
            model.addElement(emenemsinter.bubbleSort(emenemsinter.firstNameList)[i]);
        }
        jList1.setBackground(new java.awt.Color(51, 51, 51));
        jList1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(model);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent listSelectionEvent){
                boolean adjust = listSelectionEvent.getValueIsAdjusting();
                System.out.println(", Adjusting? " + adjust);
                if (!adjust) {
                    JList list = (JList) listSelectionEvent.getSource();
                    int selections[] = list.getSelectedIndices();
                    Object selectionValues[] = list.getSelectedValues();
                    for (int i = 0, n = selections.length; i < n; i++) {
                        if (i == 0) {
                            System.out.println(" Selections: ");
                        }
                        System.out.println(selections[i] + "/" + selectionValues[i] + " ");
                        String[] Entry = emenemsinter.searchRow(selectionValues[i].toString(),emenemsinter.firstNameList);
                        LastNameOutput.setText(Entry[1]);
                        FirstNameOutput.setText(Entry[0]);
                        BirthdayOutput.setText(Entry[2]);
                        AddressOutput.setText(Entry[3]);
                        EmailOutput.setText(Entry[4]);
                        NumberOutput.setText(Entry[5]);
                    }
                }

            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Last Name:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("First Name:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Birthday:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Number:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Address:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Email:");

        LastNameOutput.setBackground(new java.awt.Color(255, 255, 255));
        LastNameOutput.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        LastNameOutput.setForeground(new java.awt.Color(255, 255, 255));

        FirstNameOutput.setBackground(new java.awt.Color(255, 255, 255));
        FirstNameOutput.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        FirstNameOutput.setForeground(new java.awt.Color(255, 255, 255));

        BirthdayOutput.setBackground(new java.awt.Color(255, 255, 255));
        BirthdayOutput.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BirthdayOutput.setForeground(new java.awt.Color(255, 255, 255));

        NumberOutput.setBackground(new java.awt.Color(255, 255, 255));
        NumberOutput.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        NumberOutput.setForeground(new java.awt.Color(255, 255, 255));

        AddressOutput.setBackground(new java.awt.Color(255, 255, 255));
        AddressOutput.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        AddressOutput.setForeground(new java.awt.Color(255, 255, 255));

        EmailOutput.setBackground(new java.awt.Color(255, 255, 255));
        EmailOutput.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        EmailOutput.setForeground(new java.awt.Color(255, 255, 255));

        UpdateEntry.setBackground(new java.awt.Color(153, 255, 153));
        UpdateEntry.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        UpdateEntry.setText("Update User");
        UpdateEntry.setToolTipText("");
        UpdateEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UpdateEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEntryActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(153, 255, 153));
        SearchButton.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        DeleteEntry.setBackground(new java.awt.Color(153, 255, 153));
        DeleteEntry.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        DeleteEntry.setText("Delete User");
        DeleteEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DeleteEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEntryActionPerformed(evt);
            }
        });

        AddEntry.setBackground(new java.awt.Color(153, 255, 153));
        AddEntry.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        AddEntry.setText("New User");
        AddEntry.setToolTipText("");
        AddEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthdayOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddressOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastNameOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstNameOutput)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(DeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FirstNameOutput))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LastNameOutput))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BirthdayOutput))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumberOutput))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AddressOutput))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmailOutput))
                .addGap(38, 38, 38))
        );

        title.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        title.setText("OLIVA PHONEBOOK APP");

        title1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        title1.setText("o===o===o===o   LIST OF USERS   o===o===o===o");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(title1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(174, 174, 174))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void keyStrokeValidate(KeyEvent ke,JTextField InputComponent, int CharCount){
        String field = InputComponent.getText();
        if ((( ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9')&& field.length()  <= CharCount-1)
            ||(ke.getKeyChar() == '-')
            || ke.getKeyCode() == KeyEvent.VK_BACK_SPACE
            || ke.getKeyCode() == KeyEvent.VK_DELETE
            ){
            InputComponent.setEditable(true);
        } else{
            InputComponent.setEditable(false);
        }
    }
    private static boolean InputVerifier(String date,String Email,String number) {
        if (date.matches("^[0-9/]*$")&&Email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")&&number.matches("^[0-9.-]*$")){
            System.out.println("Data Passes Regex Verification");
            return true;     
        } else{
            System.out.println("Data Did not Pass Regex Verification");
            return false;
        }
    }
    public static int indexLocate(DefaultListModel<String> model, String input){
            int i;
            for (i=0;i<model.size();i++){
                //for (int j = i+1;j<model.size();j++){
                    if(model.get(i).compareTo(input) > 0){
                        //System.out.println("<0 " + model.get(i).compareTo(input));
                        break;

                    }
                //}
            }
            return i;
        }
    public static String convertToTitleCaseIteratingChars(String text) {
    if (text == null || text.isEmpty()) {
        return text;
    }

    StringBuilder converted = new StringBuilder();

    boolean convertNext = true;
    for (char ch : text.toCharArray()) {
        if (Character.isSpaceChar(ch)) {
            convertNext = true;
        } else if (convertNext) {
            ch = Character.toTitleCase(ch);
            convertNext = false;
        } else {
            ch = Character.toLowerCase(ch);
        }
        converted.append(ch);
    }

    return converted.toString();
    }
    private void AddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryActionPerformed
        AddEntryDialog.setVisible(true);

        
    }//GEN-LAST:event_AddEntryActionPerformed
    

    private void UpdateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEntryActionPerformed
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Error: No Info to Update");
            JOptionPane.showMessageDialog(rootPane,"Error: No Info to Update","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            UpdateEntryDialog.setVisible(true);
            FirstNameTextField.setText(FirstNameOutput.getText());
            LastNameTextField.setText(LastNameOutput.getText());
            AddressTextField.setText(AddressOutput.getText());
            String[] DateSplices = BirthdayOutput.getText().split("/");
            BirthDayTextField.setText(DateSplices[0]);
            BirthMonthTextField.setText(DateSplices[1]);
            BirthYearTextField.setText(DateSplices[2]);
            EmailTextField.setText(EmailOutput.getText());
            NumberTextField.setText(NumberOutput.getText());
        }
        
        
    }//GEN-LAST:event_UpdateEntryActionPerformed
    private static void DeleteGUIChoice(DefaultListModel<String> model, String input ){
        try{
            int i;
            for (i=0;i<model.size();i++){
                    if(model.get(i).equals(input)){
                        model.remove(i);
                        System.out.println("GUI block removed");
                        break;
                    }
            }
        }catch(Exception err){
            System.out.println(err);
        }
        
    }
    private void DeleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEntryActionPerformed
        // TODO add your handling code here:
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Error: No Info to Delete");
            JOptionPane.showMessageDialog(rootPane,"Error: No Info to Delete","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String[] choices= {"Yes","No"};
            int response=JOptionPane.showOptionDialog(this, "Do you confirm the Deletion of These Data?", "Deletion Confirmation", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, choices, choices[0]);
            switch (response) {
                case 0 -> {
                    emenemsinter.deleteRow(FirstNameOutput.getText(), EmailOutput.getText());
                    DeleteGUIChoice(model,FirstNameOutput.getText());
                    System.out.println("Data Deleted");
                    FirstNameOutput.setText("");
                    LastNameOutput.setText("");
                    AddressOutput.setText("");
                    BirthdayOutput.setText("");
                    EmailOutput.setText("");
                    NumberOutput.setText("");
                    emenemsinter.getAllRows();
                }
                case 1 -> System.out.println("Deletion cancelled");
                default -> System.out.println("No Choice");
            }
        }
    }//GEN-LAST:event_DeleteEntryActionPerformed

    private void BirthDayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDayInputActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void BirthDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BirthDayTextFieldActionPerformed

    private void NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void AddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String NewBirthDate = BirthDayTextField.getText()+"/"+BirthMonthTextField.getText()+"/"+BirthYearTextField.getText();
        if(InputVerifier(NewBirthDate, EmailTextField.getText(),NumberTextField.getText())){
            emenemsinter.updateRow(FirstNameOutput.getText(),emenemsinter.firstNameList, FirstNameTextField.getText());
            emenemsinter.updateRow(FirstNameOutput.getText(),emenemsinter.lastNameList, LastNameTextField.getText());
            emenemsinter.updateRow(FirstNameOutput.getText(),emenemsinter.BirthdayList, NewBirthDate);
            emenemsinter.updateRow(FirstNameOutput.getText(),emenemsinter.numberList, NumberTextField.getText());
            emenemsinter.updateRow(FirstNameOutput.getText(),emenemsinter.AddressList, AddressTextField.getText());
            emenemsinter.updateRow(FirstNameOutput.getText(),emenemsinter.EmailList, EmailTextField.getText());
            model.removeElement(FirstNameOutput.getText());
            model.add(indexLocate(model,   convertToTitleCaseIteratingChars(FirstNameTextField.getText())),FirstNameTextField.getText());
            FirstNameOutput.setText(FirstNameTextField.getText());
            LastNameOutput.setText(LastNameTextField.getText());
            BirthdayOutput.setText(NewBirthDate);
            NumberOutput.setText(NumberTextField.getText());
            AddressOutput.setText(AddressTextField.getText());
            EmailOutput.setText(EmailTextField.getText());
            UpdateEntryDialog.dispose();
            emenemsinter.getAllRows();
        }else{
            JOptionPane.showMessageDialog( UpdateEntryDialog,"Error: Incorrect Data","Error",JOptionPane.ERROR_MESSAGE);
            AddEntryDialog.dispose();
        }
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UpdateEntryDialog.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddEntryBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryBackButtonActionPerformed
        // TODO add your handling code here:
        AddEntryDialog.dispose();
    }//GEN-LAST:event_AddEntryBackButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        emenemsinter.getAllRows();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BirthMonthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthInputActionPerformed

    private void BirthYearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthYearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthYearInputActionPerformed

    private void BirthMonthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthTextFieldActionPerformed

    private void LastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameInputActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try{
            String query = JOptionPane.showInputDialog(rootPane, "Search User (Case-Sensitive)");
            if (emenemsinter.SearchAllFields(query)!= null){
                String[] findings = emenemsinter.SearchAllFields(query);
                FirstNameOutput.setText(findings[0]);
                LastNameOutput.setText(findings[1]);
                BirthdayOutput.setText(findings[2]);
                AddressOutput.setText(findings[3]);
                EmailOutput.setText(findings[4]);
                NumberOutput.setText(findings[5]);
                System.out.println("Found");
                jList1.setCellRenderer(new DefaultListCellRenderer(){
                    @Override
                    public Component getListCellRendererComponent(JList list, Object value,int index, boolean isSelected, boolean cellHasFocus) {
                        super.getListCellRendererComponent(list, value, index, isSelected,cellHasFocus);
                        String num = (String) value;
                        if (num.equals(findings[0])) {
                         /* setBackground(Color.null); Remove to enable the color*/ 
                        }
                        return this;
                    }                
                });
            }
        }catch(ArrayIndexOutOfBoundsException err){
            JOptionPane.showMessageDialog(rootPane,"User not Found","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("not Found");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emenemsmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emenemsmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emenemsmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emenemsmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emenemsmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEntry;
    private javax.swing.JButton AddEntryBackButton;
    private javax.swing.JButton AddEntryBackButton1;
    private javax.swing.JDialog AddEntryDialog;
    private javax.swing.JTextField AddressInput;
    private javax.swing.JTextField AddressInput1;
    private javax.swing.JLabel AddressOutput;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField BirthDayInput;
    private javax.swing.JTextField BirthDayInput1;
    private javax.swing.JTextField BirthDayTextField;
    private javax.swing.JTextField BirthMonthInput;
    private javax.swing.JTextField BirthMonthInput1;
    private javax.swing.JTextField BirthMonthTextField;
    private javax.swing.JTextField BirthYearInput;
    private javax.swing.JTextField BirthYearInput1;
    private javax.swing.JTextField BirthYearTextField;
    private javax.swing.JLabel BirthdayOutput;
    private javax.swing.JButton DeleteEntry;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JTextField EmailInput1;
    private javax.swing.JLabel EmailOutput;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JTextField FirstNameInput1;
    private javax.swing.JLabel FirstNameOutput;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameInput;
    private javax.swing.JTextField LastNameInput1;
    private javax.swing.JLabel LastNameOutput;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField NumberInput;
    private javax.swing.JTextField NumberInput1;
    private javax.swing.JLabel NumberOutput;
    private javax.swing.JTextField NumberTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JDialog SearchDialog;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton SubmitButton1;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton UpdateEntry;
    private javax.swing.JDialog UpdateEntryDialog;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
